# Generated by Django 4.2.7 on 2023-11-07 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
